// Casos del detector de conceptos (src/ai/concepts.ts): el conjunto EXACTO de modalidades que debe salir.
// [texto, [etiquetas esperadas]]
module.exports = [
  ['dividimos la cuenta entre los tres 900', ['shared_split']],
  ['pagué mi parte de la renta con mis roomies 3500', ['shared_split']],
  ['mi mitad de la luz 380', ['shared_split']],
  ['cooperamos para el regalo y me tocaron 150', ['shared_split']],
  ['hicimos una vaquita para la pizza 90 cada quien', ['shared_split']],
  ['me depositó mi roomie su parte de la luz 400', ['shared_split']],
  ['me debe mi roomie 400 de la luz', ['owed_to_me', 'shared_split']],
  ['mi amigo me debe 500', ['owed_to_me']],
  ['todavía no me paga lo del uber 120', ['owed_to_me']],
  ['le presté 1000 a mi hermano', ['owed_to_me']],
  ['les presté lana para la renta', ['owed_to_me']],
  ['pagué por todos en el restaurante 2300', ['owed_to_me']],
  ['le debo 300 a mi hermano', ['i_owe']],
  ['me prestó mi mamá 2000', ['i_owe']],
  ['tengo que pagarle a mi roomie lo del internet 250', ['i_owe', 'shared_split']],
  ['pedí prestado 1500 para la renta', ['i_owe']],
  ['ya quedamos a mano con mi roomie', ['settlement', 'shared_split']],
  ['le pagué lo que le debía a mi amigo 600', ['settlement']],
  ['saldamos cuentas con mis compañeros de cuarto', ['settlement', 'shared_split']],
  ['me pagó lo que me debía 800', ['settlement']],
  ['netflix mensual 219', ['recurring']],
  ['suscripción de spotify 129', ['recurring']],
  ['cada quincena le doy 500 a mi mamá', ['recurring']],
  ['pago de renta todos los meses 6000', ['recurring']],
  ['mensualidad del gimnasio 599', ['recurring']],
  ['cada 2 semanas le pago a la señora de la limpieza 600', ['recurring']],
  ['cargo domiciliado de la tarjeta 450', ['recurring']],
  ['compré un refri a 12 meses sin intereses 8999', ['installments']],
  ['a 18 msi la laptop 22000', ['installments']],
  ['lo compré a plazos 3500', ['installments']],
  ['la tele en mensualidades 1200', ['installments', 'recurring']],
  ['pagué kueski pay 450', ['installments']],
  ['pedí factura de la gasolina 700', ['tax_deductible']],
  ['gasto deducible consulta del doctor 900', ['tax_deductible']],
  ['para mi declaración anual la colegiatura 4800', ['tax_deductible']],
  ['me dieron la factura del restaurante 1200', ['tax_deductible']],
  ['viáticos del viaje 2500 me lo reembolsan', ['reimbursable']],
  ['pagué de mi bolsa la comida del cliente 800', ['reimbursable']],
  ['lo paga la empresa el hotel 3200', ['reimbursable']],
  ['adelanté los gastos del viaje 4000', ['reimbursable']],
  ['compré 200 dólares para el viaje', ['foreign_currency']],
  ['pagué 50 euros de entrada', ['foreign_currency']],
  ['compra internacional de amazon 35 usd', ['foreign_currency']],
  ['cambié dólares en la casa de cambio 5000', ['foreign_currency']],
  ['voy a pagar la renta el próximo mes 6000', ['planned']],
  ['recuérdame pagar la luz', ['planned']],
  ['tengo que pagar el predial 1800', ['planned']],
  ['me toca pagar la tarjeta la próxima quincena 3000', ['planned']],
  ['cuando me paguen voy a depositar 1000', ['planned']],
  ['pagué el súper 500', []],
  ['tacos 120', []],
  ['café con mi novia 90', []],
  ['cena con mi esposa 1450', []],
  ['compré 3 cafés 150', []],
  ['gasolina 700', []],
  ['me cobraron intereses 380', []],
  ['uber al aeropuerto 280', []],
  ['pagué el predial 1800', []],
  ['consulta del dentista 600', []],
  ['dividimos la cuenta y le debo 300 a mi amigo', ['shared_split', 'i_owe']],
  ['me debe mi pareja la mitad del hotel 1800 y me lo regresa el viernes', ['owed_to_me', 'shared_split']],
  ['compré un celular a 12 meses 9000 y pedí factura', ['installments', 'tax_deductible']],
  ['netflix mensual en dólares 15', ['recurring', 'foreign_currency']],
];
