// Segunda tanda de frases NUEVAS (P1b, 2026-10-03) — escritas ANTES de ampliar el catálogo a 6–8 mil
// palabras, con foco en las áreas que el catálogo no cubría: pareja/roomies/amigos, tarjetas,
// impuestos y trámites, hospital, hijos, trabajo/negocio, apuestas, etc.
//   FRESH3: se puede mirar y usar para mejorar el motor.
//   FRESH4: SELLADA — se corre una sola vez, al final; su % es el que se reporta.
// Formato: [texto, monto, subcategoría | null, { type, alt }]
const FRESH3 = [
  // ---- pareja / roomies / amigos ----
  ['pagué mi parte de la renta con mis roomies 3500', 3500, 'house_rent'],
  ['le transferí a mi roomie lo del internet 250', 250, 'house_internet'],
  ['dividimos el súper entre los tres y me tocaron 480', 480, 'food_supermarket'],
  ['cena de aniversario con mi esposa 1450', 1450, 'life_partner', { alt: ['food_restaurant'] }],
  ['cita con mi novia en el cine 380', 380, 'ent_cinema', { alt: ['life_partner'] }],
  ['regalo para mi novia 900', 900, 'life_gifts', { alt: ['life_partner'] }],
  ['me depositó mi roomie su parte de la luz 400', 400, 'inc_reimbursement', { type: 'income' }],
  ['mi pareja me pagó la mitad del hotel 1800', 1800, 'inc_reimbursement', { type: 'income' }],
  ['le pagué a mi amigo lo que le debía 600', 600, 'debt_personal'],
  ['pagué la cuenta de todos en el restaurante 2300', 2300, 'food_restaurant'],
  ['la mitad del recibo de la luz 380', 380, 'house_electricity'],
  ['pagué el gas del depa compartido 320', 320, 'house_gas'],
  ['depósito de garantía del departamento 8000', 8000, 'house_rent'],
  ['mi parte del regalo de la oficina 150', 150, 'life_gifts'],
  // ---- tarjetas, bancos, créditos ----
  ['pagué los intereses de la tarjeta 380', 380, 'debt_interest'],
  ['me cobraron la anualidad de la tarjeta 899', 899, 'fee_bank'],
  ['pago mínimo de la tarjeta de bbva 650', 650, 'debt_creditcard'],
  ['pagué el estado de cuenta de mi tarjeta nu 4200', 4200, 'debt_creditcard'],
  ['cargo por pago tardío 350', 350, 'debt_interest'],
  ['abono a mi tarjeta de liverpool 1200', 1200, 'debt_creditcard', { alt: ['debt_appliance'] }],
  ['comisión por retiro en cajero 35', 35, 'fee_bank'],
  ['reposición de tarjeta de débito 120', 120, 'fee_bank'],
  ['pagué el kueski pay 450', 450, 'debt_bnpl', { alt: ['debt_personal'] }],
  ['liquidé mi tarjeta de crédito 15000', 15000, 'debt_creditcard'],
  ['cashback de la tarjeta 120', 120, 'inc_reimbursement', { type: 'income' }],
  ['intereses moratorios del crédito 220', 220, 'debt_interest'],
  ['pago de la anualidad del seguro de vida 2800', 2800, 'health_life_insurance'],
  ['seguro de gastos médicos mayores 9800', 9800, 'health_insurance'],
  // ---- impuestos y trámites ----
  ['pagué el predial 1800', 1800, 'tax_property'],
  ['honorarios del contador por la declaración anual 900', 900, 'tax_accounting'],
  ['pagué el isr de este mes 2300', 2300, 'tax_income'],
  ['tenencia del carro 1500', 1500, 'tax_vehicle'],
  ['multa de tránsito 1100', 1100, 'tax_fines'],
  ['pasaporte nuevo 1890', 1890, 'tax_procedures'],
  ['saqué mi acta de nacimiento 120', 120, 'tax_procedures'],
  ['renovación de licencia de manejar 900', 900, 'tax_procedures', { alt: ['tax_vehicle'] }],
  ['pago de iva 1600', 1600, 'tax_income'],
  ['el abogado me cobró 3000 por el trámite', 3000, 'tax_legal'],
  ['notario para la escritura 12000', 12000, 'tax_legal'],
  ['recargos del sat 480', 480, 'tax_fines'],
  ['me devolvieron el saldo a favor del sat 5200', 5200, 'inc_reimbursement', { type: 'income' }],
  ['aparté 1500 para los impuestos', 1500, 'sav_tax_reserve', { type: 'saving' }],
  ['refrendo vehicular 700', 700, 'tax_vehicle'],
  ['imss modalidad 40 3100', 3100, 'tax_social'],
  ['verificación vehicular 600', 600, 'trans_maintenance'],
  ['comisión por transferencia internacional 250', 250, 'fee_fx'],
  ['comisión de western union 180', 180, 'fee_fx'],
  ['cambié dólares en la casa de cambio 5000', 5000, 'fee_fx'],
  // ---- salud grande y cuidados ----
  ['parto en el hospital 25000', 25000, 'health_hospital'],
  ['cirugía de rodilla 48000', 48000, 'health_hospital'],
  ['pagué la enfermera que cuida a mi abuela 1800', 1800, 'health_homecare'],
  ['silla de ruedas 3500', 3500, 'health_equipment'],
  ['aparato auditivo 12000', 12000, 'health_equipment'],
  ['ambulancia 1500', 1500, 'health_hospital'],
  ['pañales de adulto 420', 420, 'health_homecare'],
  // ---- hijos ----
  ['pañales y fórmula del bebé 780', 780, 'life_children'],
  ['guardería de mi hijo 2800', 2800, 'life_children', { alt: ['edu_tuition'] }],
  ['juguetes para mi hija 450', 450, 'life_children'],
  ['pediatra 700', 700, 'health_doctor', { alt: ['health_specialists'] }],
  ['uniformes escolares 1200', 1200, 'edu_supplies'],
  ['ropa de bebé 600', 600, 'life_children', { alt: ['misc_clothing'] }],
  ['carriola 3500', 3500, 'life_children'],
  ['niñera 600', 600, 'life_children', { alt: ['house_domestic'] }],
  // ---- hogar y personal doméstico ----
  ['pagué a la señora de la limpieza 500', 500, 'house_domestic'],
  ['el jardinero 400', 400, 'house_domestic'],
  ['plomero 700', 700, 'house_maintenance'],
  ['cambié la chapa de la puerta 450', 450, 'house_maintenance', { alt: ['house_security'] }],
  // ---- trabajo y negocio ----
  ['renta del coworking 2500', 2500, 'misc_work'],
  ['compré material de oficina 340', 340, 'misc_work', { alt: ['edu_supplies'] }],
  ['herramienta para la chamba 800', 800, 'misc_work'],
  ['publicidad en facebook para mi negocio 1000', 1000, 'misc_work'],
  ['uniformes del personal 2000', 2000, 'misc_work'],
  // ---- ahorro / inversión ----
  ['aporté 500 a la caja de ahorro', 500, 'sav_group', { type: 'saving' }],
  ['ahorré 700 para mi hijo', 700, 'sav_kids', { type: 'saving' }],
  ['invertí 5000 en forex', 5000, 'inv_forex', { type: 'investment_buy' }],
  ['compré un centenario de oro 52000', 52000, 'inv_metals', { type: 'investment_buy' }],
  // ---- ingresos nuevos ----
  ['cobré la renta del departamento 9000', 9000, 'inc_rental', { type: 'income' }],
  ['me depositaron la pensión alimenticia 3500', 3500, 'inc_support', { type: 'income' }],
  ['me cayó la beca 1900', 1900, 'inc_support', { type: 'income' }],
  ['me llegó el reembolso del seguro 4500', 4500, 'inc_reimbursement', { type: 'income' }],
  ['me devolvieron 300 de una compra', 300, 'inc_reimbursement', { type: 'income' }],
  ['me llegó la pensión del imss 4200', 4200, 'inc_support', { type: 'income' }],
  ['vendí 3 pasteles 450', 450, 'inc_sales', { type: 'income' }],
  // ---- apuestas ----
  ['perdí 500 en el casino', 500, 'ent_gambling'],
  ['compré boletos de la lotería 200', 200, 'ent_gambling'],
  ['apuesta del partido en caliente 300', 300, 'ent_gambling'],
  ['melate 100', 100, 'ent_gambling'],
  // ---- educación ----
  ['examen de toefl 4500', 4500, 'edu_exams'],
  ['titulación 8000', 8000, 'edu_exams', { alt: ['edu_tuition'] }],
  ['inscripción al ceneval 1200', 1200, 'edu_exams'],
  // ---- funerales ----
  ['gastos del funeral de mi abuelo 15000', 15000, 'life_funeral'],
  ['cremación 9000', 9000, 'life_funeral'],
  ['flores para el velorio 800', 800, 'life_funeral'],
];

const FRESH4 = [
  // ---- comida ----
  ['compré un kilo de limones y jitomates 48', 48, 'food_supermarket', { alt: ['food_market'] }],
  ['una torta de milanesa 70', 70, 'food_fastfood'],
  ['pedí sushi por uber eats 420', 420, 'food_delivery'],
  ['pastel de tres leches para la comida 350', 350, 'food_bakery'],
  ['tamales y atole 90', 90, 'food_fastfood'],
  ['un six de modelo 150', 150, 'food_alcohol'],
  ['botella de tequila 520', 520, 'food_alcohol'],
  ['elotes en la esquina 30', 30, 'food_fastfood', { alt: ['food_snacks'] }],
  ['helado de la michoacana 45', 45, 'food_sweets', { alt: ['food_snacks'] }],
  ['galletas y refresco 38', 38, 'food_snacks', { alt: ['food_supermarket'] }],
  ['pagué la cena en el restaurante italiano 1280', 1280, 'food_restaurant'],
  // ---- transporte ----
  ['cambio de llantas 4200', 4200, 'trans_maintenance'],
  ['lavado del carro 120', 120, 'trans_maintenance'],
  ['recarga de la tarjeta del metro 100', 100, 'trans_public'],
  ['boleto de autobús a puebla 280', 280, 'trans_public'],
  ['vuelo a cancún 3400', 3400, 'trans_flights'],
  ['caseta de la autopista 180', 180, 'trans_tolls'],
  ['cargué gasolina premium 700', 700, 'trans_gas'],
  ['un taxi del aeropuerto 350', 350, 'trans_taxi'],
  ['seguro del auto anual 7200', 7200, 'trans_car_insurance'],
  // ---- entretenimiento ----
  ['boletos para el concierto de peso pluma 2400', 2400, 'ent_concerts'],
  ['recarga de robux 200', 200, 'ent_videogames'],
  ['torneo de pádel 300', 300, 'ent_sports'],
  ['entrada al museo 90', 90, 'ent_events'],
  ['suscripción de spotify 129', 129, 'ent_streaming'],
  ['disney plus anual 1190', 1190, 'ent_streaming'],
  ['karaoke con los compas 600', 600, 'ent_karaoke'],
  ['entradas del estadio 650', 650, 'ent_events', { alt: ['ent_sports'] }],
  // ---- salud ----
  ['consulta con el dermatólogo 900', 900, 'health_specialists', { alt: ['health_doctor'] }],
  ['análisis de sangre 450', 450, 'health_labs'],
  ['ibuprofeno y vitamina c 130', 130, 'health_pharmacy'],
  ['resonancia magnética 5200', 5200, 'health_labs'],
  ['terapia con mi psicóloga 800', 800, 'health_mental'],
  ['limpieza dental 600', 600, 'health_dentist'],
  ['ortodoncia mensualidad 1500', 1500, 'health_dentist'],
  ['lentes de contacto 700', 700, 'health_vision'],
  ['proteína whey 890', 890, 'health_supplements'],
  // ---- hogar ----
  ['recibo del gas estacionario 650', 650, 'house_gas'],
  ['cambié el boiler 4800', 4800, 'house_maintenance', { alt: ['house_appliances'] }],
  ['pagué el internet de izzi 599', 599, 'house_internet'],
  ['recibo de telcel 399', 399, 'house_phone'],
  ['compré una lavadora 9500', 9500, 'house_appliances'],
  ['colchón nuevo 6000', 6000, 'house_furniture'],
  ['mudanza 2500', 2500, 'house_moving'],
  ['cuota de mantenimiento del edificio 1800', 1800, 'house_condofees'],
  ['pago de la cfe 740', 740, 'house_electricity'],
  // ---- mascotas, regalos, donaciones ----
  ['vacunas del perro 450', 450, 'life_pets'],
  ['veterinario 600', 600, 'life_pets'],
  ['arena para el gato 180', 180, 'life_pets'],
  ['regalo de navidad para mi mamá 800', 800, 'life_gifts', { alt: ['life_family_support'] }],
  ['donativo a la cruz roja 200', 200, 'life_donations'],
  ['diezmo de la iglesia 500', 500, 'life_donations'],
  // ---- educación ----
  ['libros de la prepa 1100', 1100, 'edu_supplies'],
  ['inscripción a inglés 2200', 2200, 'edu_courses', { alt: ['edu_tuition'] }],
  ['mensualidad de la universidad 7500', 7500, 'edu_tuition'],
  ['clase de matemáticas particular 300', 300, 'edu_tutoring'],
  ['curso en udemy 299', 299, 'edu_courses'],
  // ---- ropa, personal, tecnología ----
  ['jeans en zara 899', 899, 'misc_clothing'],
  ['tenis nuevos 1800', 1800, 'misc_clothing'],
  ['corte de cabello y barba 250', 250, 'misc_personal_care'],
  ['manicure 300', 300, 'misc_personal_care'],
  ['perfume 1500', 1500, 'misc_personal_care'],
  ['audífonos bluetooth 650', 650, 'misc_electronics'],
  ['funda para el celular 120', 120, 'misc_electronics'],
  ['icloud 50 gb 17', 17, 'misc_cloud'],
  ['google one 49', 49, 'misc_cloud'],
  // ---- viajes ----
  ['hotel en playa del carmen 3200', 3200, 'life_travel'],
  ['airbnb para el fin de semana 2100', 2100, 'life_travel'],
  ['renta de coche en mérida 1500', 1500, 'trans_carrental'],
  ['tour en cenotes 800', 800, 'life_travel', { alt: ['life_experiences'] }],
  // ---- deuda / ahorro / inversión ----
  ['abono del crédito del coche 4800', 4800, 'debt_car_loan'],
  ['pago de la hipoteca 11500', 11500, 'house_mortgage', { alt: ['debt_mortgage'] }],
  ['pagué mi deuda de nu 2300', 2300, 'debt_creditcard'],
  ['invertí en cetes 10000', 10000, 'inv_cetes', { type: 'investment_buy' }],
  ['compré bitcoin 3000', 3000, 'inv_crypto', { type: 'investment_buy' }],
  ['compré acciones de apple 8000', 8000, 'inv_stocks', { type: 'investment_buy' }],
  ['metí 2000 al fondo de emergencia', 2000, 'sav_emergency', { type: 'saving' }],
  ['aparté 1000 para vacaciones', 1000, 'sav_vacation', { type: 'saving' }],
  // ---- ingresos ----
  ['me cayó mi nómina 15000', 15000, 'inc_salary', { type: 'income' }],
  ['cobré un trabajo freelance 6000', 6000, 'inc_freelance', { type: 'income' }],
  ['vendí mi bici 2000', 2000, 'inc_sales', { type: 'income' }],
  ['me regalaron mil pesos mis tíos', 1000, 'inc_gifts', { type: 'income' }],
  ['me llegaron los dividendos 340', 340, 'inc_dividends', { type: 'income' }],
  ['intereses del mes 120', 120, 'inc_interest', { type: 'income' }],
  // ---- áreas nuevas (otras frases que las de FRESH3) ----
  ['predial del terreno 950', 950, 'tax_property'],
  ['pago provisional del sat 1700', 1700, 'tax_income'],
  ['placas nuevas del auto 1200', 1200, 'tax_vehicle'],
  ['infracción por estacionarme mal 900', 900, 'tax_fines'],
  ['visa americana 3600', 3600, 'tax_procedures'],
  ['honorarios del contador 1200', 1200, 'tax_accounting'],
  ['cuota anual de la tarjeta platinum 2500', 2500, 'fee_bank'],
  ['intereses de la tarjeta de crédito 640', 640, 'debt_interest'],
  ['pagué los honorarios del abogado 4000', 4000, 'tax_legal'],
  ['cirugía de apendicitis 38000', 38000, 'health_hospital'],
  ['muletas 450', 450, 'health_equipment'],
  ['compré una carriola 2900', 2900, 'life_children'],
  ['cena romántica con mi esposo 1700', 1700, 'life_partner', { alt: ['food_restaurant'] }],
  ['pagué a la persona que cuida a mi mamá 2500', 2500, 'health_homecare'],
  ['lotería nacional 50', 50, 'ent_gambling'],
  ['coworking del mes 1800', 1800, 'misc_work'],
  ['cobré el alquiler 7500', 7500, 'inc_rental', { type: 'income' }],
  ['me depositaron la beca 3000', 3000, 'inc_support', { type: 'income' }],
  ['me reembolsaron el gasto del viaje 2300', 2300, 'inc_reimbursement', { type: 'income' }],
  ['ahorré 900 para la universidad de mis hijos', 900, 'sav_kids', { type: 'saving', alt: ['sav_education_fund'] }],
  ['seguro de vida 3200', 3200, 'health_life_insurance'],
  ['cuota del funeral 8000', 8000, 'life_funeral'],
];

module.exports = { FRESH3, FRESH4 };
