// Tercera tanda de frases NUEVAS (P1b, 2026-10-03), escrita DESPUÉS de ampliar el catálogo y de corregir lo
// que mostró el sellado anterior (fresco_4). FRESH5: SELLADA — se corre una sola vez; su % es el que se reporta.
// Formato: [texto, monto, subcategoría | null, { type, alt }]
const FRESH5 = [
  // ---- pareja, roomies, amigos ----
  ['le pagué a mi roomie los 350 de la parte del internet', 350, 'house_internet'],
  ['pagamos a medias el airbnb y a mí me tocaron 1900', 1900, 'life_travel'],
  ['mi novia me regresó lo del cine 190', 190, 'inc_reimbursement', { type: 'income' }],
  ['salimos a cenar mi esposa y yo y gasté 980', 980, 'food_restaurant', { alt: ['life_partner'] }],
  ['compartimos el netflix con mis roomies y puse 73', 73, 'ent_streaming'],
  ['mi amigo me depositó los 500 que le presté', 500, 'inc_reimbursement', { type: 'income' }],
  ['coperacha para el pastel de la jefa 80', 80, 'food_bakery', { alt: ['life_gifts', 'life_celebration'] }],
  // ---- tarjetas y bancos ----
  ['me cargaron la anualidad del banco 720', 720, 'fee_bank'],
  ['pagué el mínimo de mi tarjeta de liverpool 540', 540, 'debt_creditcard', { alt: ['debt_appliance'] }],
  ['liquidé todo lo que debía en la tarjeta 8300', 8300, 'debt_creditcard'],
  ['cobro de comisión por no mantener saldo mínimo 150', 150, 'fee_bank'],
  ['me cobraron intereses moratorios del crédito del carro 410', 410, 'debt_interest'],
  ['compré a plazos con aplazo unos tenis 1600', 1600, 'misc_clothing', { alt: ['debt_bnpl'] }],
  ['comisión por enviar dinero al extranjero 230', 230, 'fee_fx'],
  ['abono extra a la hipoteca 6000', 6000, 'house_mortgage', { alt: ['debt_mortgage'] }],
  // ---- impuestos y trámites ----
  ['pagué la tenencia vehicular de este año 1250', 1250, 'tax_vehicle'],
  ['anticipo para el contador por la declaración 700', 700, 'tax_accounting'],
  ['saqué el pasaporte de mi hijo 1420', 1420, 'tax_procedures'],
  ['le pagué al gestor por los trámites de las placas 600', 600, 'tax_legal', { alt: ['tax_procedures', 'tax_vehicle'] }],
  ['honorarios de la notaria por la escritura 18500', 18500, 'tax_legal'],
  ['pago de isr del trimestre 3100', 3100, 'tax_income'],
  ['multa por estacionarme en doble fila 1100', 1100, 'tax_fines'],
  ['acta de matrimonio certificada 150', 150, 'tax_procedures'],
  ['predial del depa 2040', 2040, 'tax_property'],
  // ---- hogar ----
  ['pagué el recibo de totalplay 649', 649, 'house_internet'],
  ['llegó la pipa de agua y me cobraron 1100', 1100, 'house_water'],
  ['cambié los focos del baño por unos led 180', 180, 'house_maintenance', { alt: ['house_electricity'] }],
  ['compré un sillón en ikea 7200', 7200, 'house_furniture'],
  ['el plomero cobró 850 por arreglar la fuga', 850, 'house_maintenance'],
  ['pagué al jardinero del mes 600', 600, 'house_domestic'],
  ['instalaron una alarma en la casa 3800', 3800, 'house_security'],
  ['mudanza del depa con fletes 4500', 4500, 'house_moving'],
  ['pago de luz bimestral cfe 560', 560, 'house_electricity'],
  ['gas natural de naturgy 290', 290, 'house_gas'],
  ['lavamos las cobijas en la lavandería 240', 240, 'house_laundry_service'],
  // ---- comida y bebida ----
  ['tacos de birria con consomé 160', 160, 'food_fastfood'],
  ['una torta ahogada y agua de jamaica 95', 95, 'food_fastfood', { alt: ['food_restaurant', 'food_juice_bar'] }],
  ['compré fruta y verdura en la central de abastos 420', 420, 'food_market', { alt: ['food_supermarket'] }],
  ['café y pan en starbucks 150', 150, 'food_coffee'],
  ['pedí una pizza por rappi 330', 330, 'food_delivery'],
  ['un six de victoria para el partido 140', 140, 'food_alcohol'],
  ['pastel de cumpleaños de mi mamá 520', 520, 'food_bakery'],
  ['cena en el restaurante de mariscos 1450', 1450, 'food_restaurant'],
  ['helado de pistache 68', 68, 'food_sweets'],
  ['garrafón de agua ciel 45', 45, 'food_water_delivery'],
  ['súper de la quincena en chedraui 1980', 1980, 'food_supermarket'],
  ['licuado de proteína en el gym 70', 70, 'food_juice_bar'],
  // ---- transporte ----
  ['lavaron mi coche 130', 130, 'trans_maintenance'],
  ['pasaje en metrobús 6', 6, 'trans_public'],
  ['pagué la caseta a querétaro 165', 165, 'trans_tolls'],
  ['llené el tanque de gasolina magna 820', 820, 'trans_gas'],
  ['estacionamiento del aeropuerto 3 días 980', 980, 'trans_parking'],
  ['un didi al trabajo 74', 74, 'trans_didi'],
  ['boleto de ado a oaxaca 690', 690, 'trans_public', { alt: ['trans_flights'] }],
  ['cambio de aceite y filtro 780', 780, 'trans_maintenance'],
  ['renta de coche en cancún por tres días 2400', 2400, 'trans_carrental'],
  ['seguro del coche con qualitas 6800', 6800, 'trans_car_insurance'],
  // ---- salud ----
  ['consulta con la ginecóloga 1100', 1100, 'health_specialists', { alt: ['health_doctor'] }],
  ['medicinas para la alergia 260', 260, 'health_pharmacy'],
  ['limpieza dental y revisión 750', 750, 'health_dentist'],
  ['análisis de laboratorio en el chopo 900', 900, 'health_labs'],
  ['mi sesión de terapia 900', 900, 'health_mental'],
  ['lentes nuevos con micas progresivas 3200', 3200, 'health_vision'],
  ['estudio de resonancia de rodilla 5800', 5800, 'health_labs'],
  ['una noche de hospital para mi papá 7400', 7400, 'health_hospital'],
  ['pañales de adulto para mi abuelo 380', 380, 'health_homecare'],
  ['vitamina d y omega 3 420', 420, 'health_supplements'],
  // ---- hijos, mascotas, familia ----
  ['juguetes en la juguetería para mi sobrino 600', 600, 'life_children', { alt: ['life_gifts'] }],
  ['pagué la guardería del mes 3200', 3200, 'life_children', { alt: ['edu_tuition'] }],
  ['croquetas royal canin 780', 780, 'life_pets'],
  ['baño y corte de pelo de mi perro 350', 350, 'life_pets'],
  ['le mandé 1500 a mi abuela', 1500, 'life_family_support'],
  ['regalo del día de las madres 650', 650, 'life_gifts'],
  ['donativo a la cruz roja 300', 300, 'life_donations'],
  ['pagamos el velorio y la cremación 22000', 22000, 'life_funeral'],
  ['vestido para la boda de mi prima 1800', 1800, 'misc_clothing', { alt: ['life_wedding'] }],
  // ---- educación y trabajo ----
  ['colegiatura de marzo 5200', 5200, 'edu_tuition'],
  ['libros de la universidad 1350', 1350, 'edu_supplies'],
  ['clases de inglés en línea 900', 900, 'edu_courses'],
  ['regularización de matemáticas para mi hijo 400', 400, 'edu_tutoring'],
  ['examen de certificación de inglés 3900', 3900, 'edu_exams', { alt: ['edu_courses'] }],
  ['herramientas para el taller 1250', 1250, 'misc_work', { alt: ['house_maintenance'] }],
  ['mensualidad del coworking 2100', 2100, 'misc_work'],
  ['publicidad en instagram para mi tienda 800', 800, 'misc_work'],
  ['pago a proveedores de la semana 5400', 5400, 'misc_work'],
  // ---- ocio y tecnología ----
  ['boletos de cinépolis 220', 220, 'ent_cinema'],
  ['gimnasio mensualidad de smart fit 449', 449, 'ent_sports'],
  ['tarjeta de playstation 500', 500, 'ent_videogames'],
  ['entrada al museo de antropología 95', 95, 'ent_events'],
  ['spotify familiar 179', 179, 'ent_streaming'],
  ['jugamos boliche 360', 360, 'ent_bowling'],
  ['compré fichas para las maquinitas 100', 100, 'ent_arcade'],
  ['hotel en puerto vallarta 2800', 2800, 'life_travel'],
  ['vuelo de volaris a tijuana 1950', 1950, 'trans_flights'],
  ['audífonos jbl nuevos 1100', 1100, 'misc_electronics'],
  ['suscripción a chatgpt plus 400', 400, 'misc_software'],
  ['pantalla del celular rota reparación 1200', 1200, 'misc_repairs'],
  ['dropbox almacenamiento 190', 190, 'misc_cloud'],
  ['apuesta en caliente 200', 200, 'ent_gambling'],
  // ---- ropa y cuidado ----
  ['tenis nuevos en el centro comercial 1700', 1700, 'misc_clothing'],
  ['corte de pelo y tinte 900', 900, 'misc_personal_care'],
  ['manicure y pedicure 520', 520, 'misc_personal_care'],
  ['masaje relajante 700', 700, 'misc_wellness'],
  ['pedido de amazon 640', 640, 'misc_shopping'],
  ['compré en el bazar una chamarra 250', 250, 'misc_second_hand', { alt: ['misc_clothing'] }],
  // ---- ingresos ----
  ['me depositaron la quincena 9800', 9800, 'inc_salary', { type: 'income' }],
  ['me pagó el cliente por el diseño 4500', 4500, 'inc_freelance', { type: 'income' }],
  ['cobré el alquiler del local 6000', 6000, 'inc_rental', { type: 'income' }],
  ['vendí mi bici usada 1500', 1500, 'inc_sales', { type: 'income' }],
  ['me llegó el reembolso de amazon 380', 380, 'inc_reimbursement', { type: 'income' }],
  ['me cayó el ptu 8200', 8200, 'inc_bonus', { type: 'income' }],
  ['me depositó mi papá la mesada 1500', 1500, 'inc_allowance', { type: 'income' }],
  ['dividendos de fibra uno 560', 560, 'inc_dividends', { type: 'income' }],
  ['me regalaron dinero mis abuelos 1000', 1000, 'inc_gifts', { type: 'income' }],
  // ---- ahorro e inversión ----
  ['aparté 2500 para el fondo de emergencia', 2500, 'sav_emergency', { type: 'saving' }],
  ['aparté 1000 para el enganche de la casa', 1000, 'sav_house_downpayment', { type: 'saving' }],
  ['ahorré 800 para la boda', 800, 'sav_wedding_fund', { type: 'saving' }],
  ['metí 1200 a mi ppr', 1200, 'sav_retirement', { type: 'saving' }],
  ['compré etf de vanguard 5000', 5000, 'inv_etfs', { type: 'investment_buy' }],
  ['invertí en fibras 3000', 3000, 'inv_fibras', { type: 'investment_buy' }],
  ['compré ethereum 2000', 2000, 'inv_crypto', { type: 'investment_buy' }],
  ['compré dos onzas de plata libertad 1900', 1900, 'inv_metals', { type: 'investment_buy' }],
];

module.exports = { FRESH5 };
