// Casos escritos a mano con la respuesta correcta según criterio humano.
// Cada caso lista solo los campos que se evalúan.

// [texto, { type, amount, categoryId, subcategoryId }]
const TIPOS = [
  // ingresos
  ['me pagaron 8500 de la quincena', { type: 'income', amount: 8500, subcategoryId: 'inc_salary' }],
  ['me depositaron la nómina 12000', { type: 'income', amount: 12000, subcategoryId: 'inc_salary' }],
  ['sueldo 15000', { type: 'income', amount: 15000, subcategoryId: 'inc_salary' }],
  ['cobré mi quincena 6200', { type: 'income', amount: 6200, subcategoryId: 'inc_salary' }],
  ['llegó mi sueldo de 18000 pesos', { type: 'income', amount: 18000, subcategoryId: 'inc_salary' }],
  ['depósito de nómina 9800', { type: 'income', amount: 9800, subcategoryId: 'inc_salary' }],
  ['recibí mi aguinaldo de 15000', { type: 'income', amount: 15000, subcategoryId: 'inc_bonus' }],
  ['me dieron mi bono de 5000', { type: 'income', amount: 5000, subcategoryId: 'inc_bonus' }],
  ['me cayó el reparto de utilidades 9000', { type: 'income', amount: 9000, subcategoryId: 'inc_bonus' }],
  ['cobré 7000 de un trabajo freelance', { type: 'income', amount: 7000, subcategoryId: 'inc_freelance' }],
  ['ingreso extra por una chamba 1500', { type: 'income', amount: 1500, subcategoryId: 'inc_freelance' }],
  ['vendí mi bici en 2000', { type: 'income', amount: 2000, subcategoryId: 'inc_sales' }],
  ['vendí unos tenis usados por 600', { type: 'income', amount: 600, subcategoryId: 'inc_sales' }],
  ['vendí mi celular viejo en 3500 pesos', { type: 'income', amount: 3500, subcategoryId: 'inc_sales' }],
  ['me regalaron 500 pesos', { type: 'income', amount: 500, subcategoryId: 'inc_gifts' }],
  ['me regalaron dinero 1000', { type: 'income', amount: 1000, subcategoryId: 'inc_gifts' }],
  ['mi mamá me dio mi mesada de 1000', { type: 'income', amount: 1000, subcategoryId: 'inc_allowance' }],
  ['me llegó la mesada 800', { type: 'income', amount: 800, subcategoryId: 'inc_allowance' }],
  ['me llegaron intereses de 120 pesos', { type: 'income', amount: 120, subcategoryId: 'inc_interest' }],
  ['cobré dividendos por 450', { type: 'income', amount: 450, subcategoryId: 'inc_dividends' }],
  ['rendimientos de 300 pesos', { type: 'income', amount: 300, subcategoryId: 'inc_investments' }],
  ['me pagaron 3500 de mi sueldo', { type: 'income', amount: 3500, subcategoryId: 'inc_salary' }],
  ['me depositaron 2000 de un cliente', { type: 'income', amount: 2000, categoryId: 'income' }],
  ['me cayó mi quincena de 7400', { type: 'income', amount: 7400, subcategoryId: 'inc_salary' }],
  ['me dieron el aguinaldo 20000', { type: 'income', amount: 20000, subcategoryId: 'inc_bonus' }],

  // ahorro
  ['ahorré 500 pesos', { type: 'saving', amount: 500 }],
  ['guardé 300 para vacaciones', { type: 'saving', amount: 300, subcategoryId: 'sav_vacation' }],
  ['metí 1000 al fondo de emergencia', { type: 'saving', amount: 1000, subcategoryId: 'sav_emergency' }],
  ['ahorré 2000 para el enganche de la casa', { type: 'saving', amount: 2000, subcategoryId: 'sav_house_downpayment' }],
  ['aporté 1500 a mi afore', { type: 'saving', amount: 1500, subcategoryId: 'sav_retirement' }],
  ['guardé 800 en mi meta de la laptop', { type: 'saving', amount: 800, subcategoryId: 'sav_goals' }],
  ['metí 600 a mis ahorros', { type: 'saving', amount: 600 }],
  ['separé 500 para ahorro', { type: 'saving', amount: 500 }],
  ['ahorré 1000 para estudios', { type: 'saving', amount: 1000, subcategoryId: 'sav_education_fund' }],
  ['guardé 400 pesos para el fondo de emergencia', { type: 'saving', amount: 400, subcategoryId: 'sav_emergency' }],
  ['ahorré 250 de mi quincena', { type: 'saving', amount: 250 }],
  ['metí 700 al fondo de vacaciones', { type: 'saving', amount: 700, subcategoryId: 'sav_vacation' }],
  ['aparté 900 para mi retiro', { type: 'saving', amount: 900, subcategoryId: 'sav_retirement' }],

  // inversión
  ['invertí 2000 en cetes', { type: 'investment_buy', amount: 2000, subcategoryId: 'inv_cetes' }],
  ['compré 3 acciones de apple por 1500 pesos', { type: 'investment_buy', amount: 1500, subcategoryId: 'inv_stocks' }],
  ['compré etf voo 2500', { type: 'investment_buy', amount: 2500, subcategoryId: 'inv_etfs' }],
  ['invertí 1000 en bitcoin', { type: 'investment_buy', amount: 1000, subcategoryId: 'inv_crypto' }],
  ['compré bitcoin por 500', { type: 'investment_buy', amount: 500, subcategoryId: 'inv_crypto' }],
  ['metí 3000 a cetesdirecto', { type: 'investment_buy', amount: 3000, subcategoryId: 'inv_cetes' }],
  ['invertí 5000 en fibras', { type: 'investment_buy', amount: 5000, subcategoryId: 'inv_fibras' }],
  ['compré fibra funo por 2000', { type: 'investment_buy', amount: 2000, subcategoryId: 'inv_fibras' }],
  ['compré unos bonos del gobierno por 4000', { type: 'investment_buy', amount: 4000, subcategoryId: 'inv_bonds' }],
  ['invertí 1500 en un fondo de inversión', { type: 'investment_buy', amount: 1500, subcategoryId: 'inv_funds' }],
  ['compré ethereum 800 pesos', { type: 'investment_buy', amount: 800, subcategoryId: 'inv_crypto' }],
  ['compré acciones de tesla 3000', { type: 'investment_buy', amount: 3000, subcategoryId: 'inv_stocks' }],
  ['invertí 6000 en gbm', { type: 'investment_buy', amount: 6000, subcategoryId: 'inv_stocks' }],
  ['compré udibonos por 2500', { type: 'investment_buy', amount: 2500, subcategoryId: 'inv_cetes' }],

  // gastos normales que NO deben confundirse con ingreso/ahorro/inversión
  ['pagué 120 de un regalo para mi mamá', { type: 'expense', amount: 120, subcategoryId: 'life_gifts' }],
  ['gasté 300 en una cena con mi pareja en un restaurante', { type: 'expense', amount: 300, subcategoryId: 'food_restaurant' }],
  ['compré un libro de ahorro personal por 250', { type: 'expense', amount: 250, subcategoryId: 'edu_supplies' }],
  ['pagué 90 del bono de transporte escolar', { type: 'expense', amount: 90, subcategoryId: 'trans_school' }],
  ['me cobraron 45 de comisión', { type: 'expense', amount: 45, categoryId: null, missing: ['category'] }],
  ['pagué 800 de la inscripción del curso de inversión', { type: 'expense', amount: 800, categoryId: 'education' }],
  ['gasté 200 en un cargador', { type: 'expense', amount: 200, subcategoryId: 'misc_electronics' }],
  ['pagué la guardería 2500', { type: 'expense', amount: 2500 }],
];

// [texto, { categoryId, subcategoryId }]  — null en categoryId = hay que preguntar
const GAS = [
  ['50 de gas al coche', { subcategoryId: 'trans_gas' }],
  ['cargué gas en la gasolinera 600', { subcategoryId: 'trans_gas' }],
  ['gas del carro 500', { subcategoryId: 'trans_gas' }],
  ['300 de gas para la camioneta', { subcategoryId: 'trans_gas' }],
  ['gas premium 700', { subcategoryId: 'trans_gas' }],
  ['gas magna 450', { subcategoryId: 'trans_gas' }],
  ['lleno de gas al auto 800', { subcategoryId: 'trans_gas' }],
  ['gas diesel 900', { subcategoryId: 'trans_gas' }],
  ['pagué 400 de gas, fueron 20 litros', { subcategoryId: 'trans_gas' }],
  ['gas lp 350', { subcategoryId: 'house_gas' }],
  ['pagué el gas de la casa 420', { subcategoryId: 'house_gas' }],
  ['recarga del cilindro de gas 500', { subcategoryId: 'house_gas' }],
  ['gas natural 250', { subcategoryId: 'house_gas' }],
  ['gas de la estufa 300', { subcategoryId: 'house_gas' }],
  ['gas del boiler 380', { subcategoryId: 'house_gas' }],
  ['me cobraron 600 del gas de la casa', { subcategoryId: 'house_gas' }],
  ['el gas del calentador 200', { subcategoryId: 'house_gas' }],
  ['llenado del tanque estacionario 1800', { subcategoryId: 'house_gas' }],
  ['pagué 300 de gas', { categoryId: null }],
  ['gas 450', { categoryId: null }],
  ['compré gas 380 pesos', { categoryId: null }],
  ['gasolina 500', { subcategoryId: 'trans_gas' }],
  ['pipa de gas 2500', { subcategoryId: 'house_gas' }],
  ['gas para el boiler del depa 340', { subcategoryId: 'house_gas' }],
];

// [texto con error de dictado/tecleo, subcategoría correcta]
const TYPOS = [
  ['totillas 50', 'food_supermarket'],
  ['aguakate 30', 'food_supermarket'],
  ['gazolina 400', 'trans_gas'],
  ['gasolna 500', 'trans_gas'],
  ['starbuks 90', 'food_coffee'],
  ['cinepolis 180', 'ent_cinema'],
  ['cinépollis 200', 'ent_cinema'],
  ['mcdonals 150', 'food_fastfood'],
  ['mcrobus 7', 'trans_microbus', { alt: ['trans_public'] }],
  ['metrobus 6', 'trans_public'],
  ['cervesa 90', 'food_alcohol'],
  ['hamburgesa 120', 'food_fastfood'],
  ['panaderia 45', 'food_bakery'],
  ['tintoreria 200', 'house_laundry_service'],
  ['lavanderia 150', 'house_laundry_service'],
  ['farmacia 230', 'health_pharmacy'],
  ['farmasia 230', 'health_pharmacy'],
  ['dentísta 600', 'health_dentist'],
  ['dentista 600', 'health_dentist'],
  ['sicólogo 800', 'health_mental'],
  ['psicologo 800', 'health_mental'],
  ['netflis 219', 'ent_streaming'],
  ['espotify 129', 'ent_streaming'],
  ['spotifi 129', 'ent_streaming'],
  ['gimnacio 450', 'ent_sports'],
  ['gimnasio 450', 'ent_sports'],
  ['restaurant 350', 'food_restaurant'],
  ['restorante 350', 'food_restaurant'],
  ['supermercado 900', 'food_supermarket'],
  ['superrmercado 900', 'food_supermarket'],
  ['estacionamiento 40', 'trans_parking'],
  ['estacionamento 40', 'trans_parking'],
  ['mecanico 1200', 'trans_maintenance'],
  ['mecánico 1200', 'trans_maintenance'],
  ['veterinario 500', 'life_pets'],
  ['beterinario 500', 'life_pets'],
  ['colegiatura 3500', 'edu_tuition'],
  ['colegiatira 3500', 'edu_tuition'],
  ['papeleria 80', 'edu_supplies'],
  ['papelería 80', 'edu_supplies'],
  ['electricidad 450', 'house_electricity'],
  ['electrisidad 450', 'house_electricity'],
  ['hipotéca 9000', 'house_mortgage'],
  ['telmes 399', 'house_internet', { known: 'typo de 6 letras: no se corrige a propósito (riesgo de confundir palabras reales, ej. pasada/posada)' }],
  ['totalplay 499', 'house_internet'],
  ['totalpley 499', 'house_internet'],
  ['didí 90', 'trans_didi'],
  ['capuchino 65', 'food_coffee'],
  ['capuchinno 65', 'food_coffee'],
  ['chicharon 25', 'food_snacks'],
  ['dorilocos 40', 'food_snacks'],
  ['tianguiz 150', 'food_market'],
  ['gasolinera 600', 'trans_gas'],
  ['gasolinéra 600', 'trans_gas'],
  ['paga del cine 120', 'ent_cinema'],
  ['cine 120', 'ent_cinema'],
  ['seguro de auto 4200', 'trans_car_insurance'],
  ['seguro del coche 4200', 'trans_car_insurance'],
  ['pasaje 12', 'trans_public'],
  ['pasage 12', 'trans_public', { known: 'typo de 6 letras: no se corrige a propósito (riesgo de confundir palabras reales, ej. pasada/posada)' }],
  ['maquillage 350', 'misc_personal_care'],
  ['perfumme 900', 'misc_personal_care'],
  ['vitaminas 280', 'health_supplements'],
  ['vitaminnas 280', 'health_supplements'],
  ['lentes de contacto 700', 'health_vision'],
  ['lentez 600', 'health_vision', { known: 'typo de 6 letras: no se corrige a propósito (riesgo de confundir palabras reales, ej. pasada/posada)' }],
  ['ortodoncia 1500', 'health_dentist'],
  ['reparasion de celular 500', 'misc_repairs'],
];

// Frases con monto pero sin pista de categoría: lo correcto es PREGUNTAR, nunca inventar.
const SIN_CATEGORIA = [
  ['pagué 200 de lo de ayer', 200],
  ['gasté 350 en cosas', 350],
  ['me salió en 90 pesos eso', 90],
  ['pagué 150 pesos', 150],
  ['gasté 80', 80],
  ['500 pesos', 500],
  ['fueron 120 pesos', 120],
  ['me cobraron 300', 300],
  ['320 de lo que te conté', 320],
  ['pagué 75 de lo mismo de siempre', 75],
  ['lo de la semana pasada 450', 450],
  ['gasté 60 en algo', 60],
  ['unas cosas 220', 220],
  ['pagué 1000 por lo de Juan', 1000],
  ['ya pagué 90', 90],
  ['100 pesos de eso', 100],
  ['se me fueron 250 pesos', 250],
  ['lo de ayer 180', 180],
  ['pagué 430 de lo que quedamos', 430],
  ['gasté 95 en una cosa', 95],
  ['deposité para lo de mi hermano 700', 700],
  ['pagué lo de siempre 260', 260],
  ['fueron 1500 pesos', 1500],
  ['me costó 340', 340],
  ['pagué 55 pesos', 55],
  ['gasté 710 pesos hoy', 710],
  ['salieron 125 pesos', 125],
  ['pagué 2000 de lo que debía', 2000],
  ['son 99 pesos', 99],
  ['me quitaron 40 pesos', 40],
  ['una cosa de 280', 280],
  ['gasté 15', 15],
  ['pagué 600 en lo acordado', 600],
  ['unos 330 pesos', 330],
  ['gasté 405 pesos en la tarde', 405],
  ['pagué de lo de la fiesta del otro día 520', 520],
  ['costó 770 pesos', 770],
  ['pagué 85 por lo que pedí', 85],
  ['pagué 36', 36],
];

// [texto, monto esperado, moneda (default MXN)]
const MONTOS = [
  ['pagué cincuenta y cinco pesos de tortillas', 55],
  ['mil quinientos de renta', 1500],
  ['dos mil pesos de renta', 2000],
  ['$1,250.75 de súper', 1250.75],
  ['doscientos treinta y cuatro pesos de gasolina', 234],
  ['setecientos pesos de la luz', 700],
  ['tres mil doscientos de colegiatura', 3200],
  ['cien pesos de gasolina', 100],
  ['ciento cincuenta pesos de súper', 150],
  ['quince pesos de pan', 15],
  ['veinticinco pesos de metro', 25],
  ['treinta y uno pesos de café', 31],
  ['novecientos noventa y nueve pesos de zapatos', 999],
  ['cuatro mil quinientos cincuenta de renta', 4550],
  ['5 mil pesos de renta', 5000],
  ['2 mil de colegiatura', 2000],
  ['20 mil pesos de enganche', 20000],
  ['3 mil quinientos de la luz', 3500],
  ['una luca de súper', 1000],
  ['dos lucas de renta', 2000],
  ['cien dólares de netflix', 100, 'USD'],
  ['veinte dólares de spotify', 20, 'USD'],
  ['15 usd de github', 15, 'USD'],
  ['$99.90 de café', 99.9],
  ['1500.50 de súper', 1500.5],
  ['$2,000 de renta', 2000],
  ['mil pesos de gasolina', 1000],
  ['quinientos pesos de comida', 500],
  ['ochenta pesos de tacos', 80],
  ['sesenta y cinco de café', 65],
  ['cuarenta pesos de camión', 40],
  ['trescientos de farmacia', 300],
  ['seiscientos cincuenta de la tintorería', 650],
  ['mil doscientos de internet', 1200],
  ['dieciocho pesos de metro', 18],
  ['noventa de tacos', 90],
  ['setenta y cinco de pan', 75],
  ['dos mil quinientos de colegiatura', 2500],
  ['ocho mil de renta', 8000],
  ['doce mil de hipoteca', 12000],
  ['pagué $45 de camión', 45],
  ['pagué 45.50 de camión', 45.5],
  ['gasté 1,299 en tenis', 1299],
  ['gasté $12,500 en la mudanza', 12500],
  ['son 350 pesos de farmacia', 350],
  ['de café fueron 65', 65],
  ['65 pesos de café', 65],
  ['café por 65 pesos', 65],
  ['tacos 90', 90],
  ['uber 150', 150],
  ['renta 7500', 7500],
  ['luz 480', 480],
  ['trescientos veinte de la despensa', 320],
  ['pagué mil trescientos de seguro', 1300],
  ['diez pesos de chicles', 10],
  ['catorce pesos de pasaje', 14],
  ['cuatrocientos pesos de gasolina', 400],
  ['novecientos de súper', 900],
  ['quinientos cincuenta de agua', 550],
];

// Frases con más de un número: el monto es el PRECIO, no la cantidad.
const MULTI_NUMERO = [
  ['medio kilo de huevo por cuarenta pesos', 40, 'food_supermarket'],
  ['2 kilos de tortilla 38 pesos', 38, 'food_supermarket'],
  ['3 tacos por 60 pesos', 60, 'food_fastfood'],
  ['compré 2 boletos de cine por 180 pesos', 180, 'ent_cinema'],
  ['1 litro de leche en 28 pesos', 28, 'food_supermarket'],
  ['dos cervezas 90', 90, 'food_alcohol'],
  ['3 cafés 150', 150, 'food_coffee'],
  ['4 boletos de cine 320', 320, 'ent_cinema'],
  ['2 tacos de pastor 50 pesos', 50, 'food_fastfood'],
  ['10 litros de gasolina 240 pesos', 240, 'trans_gas'],
  ['5 kilos de tortillas 95 pesos', 95, 'food_supermarket'],
  ['dos boletos del metro 10 pesos', 10, 'trans_public'],
  ['compré 3 playeras por 450', 450, 'misc_clothing'],
  ['2 pizzas 380', 380, 'food_fastfood'],
  ['6 chelas 140 pesos', 140, 'food_alcohol'],
  ['un kilo de limón 35 pesos', 35, 'food_supermarket'],
  ['2 uber 300 pesos', 300, 'trans_uber'],
  ['comí 3 tacos y fueron 75 pesos', 75, 'food_fastfood'],
  ['1 cerveza 45', 45, 'food_alcohol'],
  ['pagué 500 por 2 boletos de cine', 500, 'ent_cinema'],
  ['cuarto de kilo de jamón 62 pesos', 62, 'food_supermarket'],
  ['dos cafés 110 pesos', 110, 'food_coffee'],
  ['tres boletos de concierto 2400', 2400, 'ent_concerts'],
  ['5 tacos 100', 100, 'food_fastfood'],
  ['8 litros de gasolina 190', 190, 'trans_gas'],
];

// [texto, [segmentos esperados]]
const SEGMENTOS = [
  ['cincuenta y cinco de tortillas y quince de café', ['cincuenta y cinco de tortillas', 'quince de café']],
  ['gasté 80 en uber y 120 en comida', ['gasté 80 en uber', '120 en comida']],
  ['metro 5, camión 7, café 40', ['metro 5', 'camión 7', 'café 40']],
  ['pagué 300 de luz; 250 de agua', ['pagué 300 de luz', '250 de agua']],
  ['compré pan 30 también leche 28', ['compré pan 30', 'leche 28']],
  ['café 40 y además tacos 90', ['café 40', 'tacos 90']],
  ['ayer pagué 500 de súper y también 200 de gasolina', ['ayer pagué 500 de súper', '200 de gasolina']],
  ['uber 120\ntacos 90\nmetro 5', ['uber 120', 'tacos 90', 'metro 5']],
  ['quince de café y veinte de pan', ['quince de café', 'veinte de pan']],
  ['café 45 y tacos 80 y metro 5', ['café 45', 'tacos 80', 'metro 5']],
  ['renta 7500 y luz 480', ['renta 7500', 'luz 480']],
  ['gasolina 500, súper 900', ['gasolina 500', 'súper 900']],
  ['pagué 60 de café y 45 de pan', ['pagué 60 de café', '45 de pan']],
  ['cien de gasolina y cincuenta de estacionamiento', ['cien de gasolina', 'cincuenta de estacionamiento']],
  ['tacos 90 también refresco 25', ['tacos 90', 'refresco 25']],
  ['dos mil de renta y trescientos de internet', ['dos mil de renta', 'trescientos de internet']],
  ['gasté 200 en cine y 150 en palomitas', ['gasté 200 en cine', '150 en palomitas']],
  ['uber 85; didi 70; metro 5', ['uber 85', 'didi 70', 'metro 5']],
  ['súper 850, farmacia 230, gasolina 600', ['súper 850', 'farmacia 230', 'gasolina 600']],
  ['pagué la luz 450 y el agua 280', ['pagué la luz 450', 'el agua 280']],
  // NO deben cortarse
  ['pan y leche 50 pesos', ['pan y leche 50 pesos']],
  ['tacos y refresco 90', ['tacos y refresco 90']],
  ['arroz y frijol 45 pesos', ['arroz y frijol 45 pesos']],
  ['compré cincuenta y cinco pesos de tortillas', ['compré cincuenta y cinco pesos de tortillas']],
  ['papel y lápiz 30', ['papel y lápiz 30']],
  ['pagué la luz y el agua 600', ['pagué la luz y el agua 600']],
  ['ropa y zapatos 800', ['ropa y zapatos 800']],
  ['gasté 200 en tacos y cervezas', ['gasté 200 en tacos y cervezas']],
  ['gasté 200 en tacos, refrescos y postre', ['gasté 200 en tacos, refrescos y postre']],
  ['pagué ciento veinte y cinco pesos de gasolina', ['pagué ciento veinte y cinco pesos de gasolina']],
  ['café con leche y pan 70', ['café con leche y pan 70']],
  ['gasté 90 en pizza y refresco', ['gasté 90 en pizza y refresco']],
  ['tortillas y huevo 65', ['tortillas y huevo 65']],
  ['compré jabón y shampoo por 85', ['compré jabón y shampoo por 85']],
  ['pagué 150 de luz y gas', ['pagué 150 de luz y gas']],
  ['comida y bebida 300 pesos', ['comida y bebida 300 pesos']],
  ['pagué 40 de camión', ['pagué 40 de camión']],
  ['setenta y cinco pesos de tacos', ['setenta y cinco pesos de tacos']],
  ['cuarenta y cinco de café y cincuenta y cinco de pan', ['cuarenta y cinco de café', 'cincuenta y cinco de pan']],
  ['una pizza y unas chelas 450', ['una pizza y unas chelas 450']],
  ['gasté 120 en el cine, palomitas y refresco', ['gasté 120 en el cine, palomitas y refresco']],
  ['pagué 300 de internet y teléfono', ['pagué 300 de internet y teléfono']],
  ['tacos de pastor y de suadero 110', ['tacos de pastor y de suadero 110']],
  ['pagué 500 de súper y 200 de gasolina', ['pagué 500 de súper', '200 de gasolina']],
  ['dulces y botana 60', ['dulces y botana 60']],
  ['verduras y fruta 130 pesos', ['verduras y fruta 130 pesos']],
];

// [texto, null | { direction, hintContains }]
const AJUSTES = [
  ['agrégale 500 a mi nu', { direction: 'increment', hintContains: 'nu' }],
  ['deposité 1000 en mi bbva', { direction: 'increment', hintContains: 'bbva' }],
  ['súmale 200 a mi morralla', { direction: 'increment', hintContains: 'morralla' }],
  ['métele 300 a mi tarjeta de santander', { direction: 'increment', hintContains: 'santander' }],
  ['abónale 1500 a mi cuenta de banorte', { direction: 'increment', hintContains: 'banorte' }],
  ['ingresa 800 a mi hey banco', { direction: 'increment', hintContains: 'hey' }],
  ['recarga 200 a mi tarjeta del metro', { direction: 'increment', hintContains: 'metro' }],
  ['échale 100 a mi efectivo', { direction: 'increment', hintContains: 'efectivo' }],
  ['fondea mi nu con 500', { direction: 'increment', hintContains: 'nu' }],
  ['me cayeron 500 en mi bbva', { direction: 'increment', hintContains: 'bbva' }],
  ['agrega 2000 a mi cuenta de ahorro', { direction: 'increment', hintContains: 'ahorro' }],
  ['súmale 1200 a mi tarjeta nu', { direction: 'increment', hintContains: 'nu' }],
  ['deposita 3000 en mi santander', { direction: 'increment', hintContains: 'santander' }],
  ['abona 400 a mi mercado pago', { direction: 'increment', hintContains: 'mercado' }],
  ['metí 600 a mi nu', { direction: 'increment', hintContains: 'nu' }],
  ['agrégale 150 a mi cartera', { direction: 'increment', hintContains: 'cartera' }],
  ['ingresé 5000 a mi cuenta de bbva', { direction: 'increment', hintContains: 'bbva' }],
  ['depositale 700 a mi hsbc', { direction: 'increment', hintContains: 'hsbc' }],
  ['añade 250 a mi efectivo', { direction: 'increment', hintContains: 'efectivo' }],
  ['mete 1000 a mi tarjeta de banamex', { direction: 'increment', hintContains: 'banamex' }],
  ['echa 80 a mi morralla', { direction: 'increment', hintContains: 'morralla' }],
  ['cárgale 300 a mi tarjeta de transporte', { direction: 'increment', hintContains: 'transporte' }],
  ['súmale 90 a mi cuenta de nu', { direction: 'increment', hintContains: 'nu' }],
  ['entraron 2000 a mi bbva', { direction: 'increment', hintContains: 'bbva' }],
  ['quítale 200 a mi morralla', { direction: 'decrement', hintContains: 'morralla' }],
  ['sácale 300 a mi nu', { direction: 'decrement', hintContains: 'nu' }],
  ['retira 1000 de mi bbva', { direction: 'decrement', hintContains: 'bbva' }],
  ['réstale 50 a mi efectivo', { direction: 'decrement', hintContains: 'efectivo' }],
  ['descuéntale 120 a mi tarjeta de santander', { direction: 'decrement', hintContains: 'santander' }],
  ['bájale 500 a mi santander', { direction: 'decrement', hintContains: 'santander' }],
  ['saqué 400 de mi cuenta de banorte', { direction: 'decrement', hintContains: 'banorte' }],
  ['quita 100 de mi morralla', { direction: 'decrement', hintContains: 'morralla' }],
  ['réstale 700 a mi hey banco', { direction: 'decrement', hintContains: 'hey' }],
  ['sácale 1500 a mi cuenta de ahorro', { direction: 'decrement', hintContains: 'ahorro' }],
  ['retiré 2000 de mi nu', { direction: 'decrement', hintContains: 'nu' }],
  ['disminuye 300 a mi cartera', { direction: 'decrement', hintContains: 'cartera' }],
  ['quítale 60 a mi tarjeta del metro', { direction: 'decrement', hintContains: 'metro' }],
  ['redúcele 800 a mi bbva', { direction: 'decrement', hintContains: 'bbva' }],
  ['sacar 500 de mi cuenta de hsbc', { direction: 'decrement', hintContains: 'hsbc' }],
  ['descuenta 90 de mi efectivo', { direction: 'decrement', hintContains: 'efectivo' }],
  // NO son ajustes de cuenta
  ['pagué 65 de café', null],
  ['retiré 500 del cajero', null],
  ['gasté 200 en el depósito de agua', null],
  ['ingreso 5000 de mi sueldo', null],
  ['pagué 300 de la luz', null],
  ['cargué 400 de gasolina', null],
  ['compré una carga de gas 350', null],
  ['me pagaron la quincena 8000', null],
  ['uber 120', null],
  ['compré una recarga telcel de 100', null],
  ['pagué el depósito de la renta 8000', null],
  ['gasté 90 en tacos', null],
  ['la renta 7500', null],
  ['sueldo 15000', null],
  ['me cobraron la suma de 300 por el seguro', null],
];

module.exports = { TIPOS, GAS, TYPOS, SIN_CATEGORIA, MONTOS, MULTI_NUMERO, SEGMENTOS, AJUSTES };
