// Vocabulario del golden set: cómo hablaría una persona en México de cada
// subcategoría. La etiqueta correcta la fija este archivo (criterio humano),
// NUNCA se copia de lo que responde el parser — si no, la prueba sería circular.
// [categoría, subcategoría, [frases]]
module.exports = [
  // ---------- Miscelánea ----------
  ['miscellaneous', 'misc_clothing', ['unos jeans', 'una playera', 'tenis nuevos', 'un vestido', 'una chamarra', 'zapatos de vestir', 'calcetines y ropa interior', 'ropa en zara', 'un suéter', 'una gorra']],
  ['miscellaneous', 'misc_wellness', ['un masaje', 'spa', 'temazcal', 'masaje de espalda', 'baño de vapor', 'sesión de reiki']],
  ['miscellaneous', 'misc_personal_care', ['corte de pelo', 'barbería', 'uñas acrílicas', 'manicure', 'maquillaje', 'perfume', 'tinte de cabello', 'depilación láser', 'pedicure']],
  ['miscellaneous', 'misc_shopping', ['compras en amazon', 'algo en mercado libre', 'cosas en la tienda', 'un pedido de temu', 'compras en liverpool']],
  ['miscellaneous', 'misc_electronics', ['audífonos', 'un cargador', 'celular nuevo', 'una laptop', 'una tablet', 'mouse inalámbrico', 'bocina bluetooth', 'cable usb', 'un teclado']],
  ['miscellaneous', 'misc_software', ['licencia de office', 'chatgpt', 'hosting', 'dominio de la página', 'app store', 'suscripción a claude', 'github', 'adobe', 'google play']],
  ['miscellaneous', 'misc_cloud', ['icloud', 'google one', 'dropbox', 'almacenamiento en la nube', 'espacio en la nube']],
  ['miscellaneous', 'misc_repairs', ['reparación de celular', 'cambio de pantalla', 'servicio técnico de la laptop', 'taller de electrónica', 'arreglo de la tele']],
  ['miscellaneous', 'misc_second_hand', ['venta de garage', 'facebook marketplace', 'trueque', 'algo de segunda mano']],

  // ---------- Alojamiento y servicios ----------
  ['housing', 'house_rent', ['renta', 'la renta del depa', 'alquiler', 'renta del cuarto', 'pago del departamento']],
  ['housing', 'house_mortgage', ['hipoteca', 'crédito hipotecario', 'infonavit', 'fovissste', 'pago de la hipoteca']],
  ['housing', 'house_insurance', ['seguro de casa', 'seguro del hogar', 'póliza del hogar']],
  ['housing', 'house_phone', ['telcel', 'recarga de celular', 'plan telefónico', 'at&t', 'movistar', 'recarga telcel']],
  ['housing', 'house_internet', ['internet', 'wifi', 'telmex', 'izzi', 'totalplay', 'megacable', 'recibo del internet']],
  ['housing', 'house_electricity', ['la luz', 'recibo de luz', 'cfe', 'electricidad']],
  ['housing', 'house_water', ['el agua', 'recibo del agua', 'sacmex', 'pago del agua']],
  ['housing', 'house_gas', ['gas lp', 'cilindro de gas', 'gas natural', 'naturgy', 'tanque de gas', 'pipa de gas']],
  ['housing', 'house_maintenance', ['mantenimiento de la casa', 'predial', 'plomero', 'electricista', 'pintura para la casa', 'arreglo del baño']],
  ['housing', 'house_condofees', ['condominio', 'cuota de mantenimiento del edificio', 'administración del edificio', 'vigilancia del edificio']],
  ['housing', 'house_furniture', ['muebles', 'colchón', 'un sillón', 'comedor', 'escritorio nuevo', 'librero', 'closet']],
  ['housing', 'house_appliances', ['refrigerador', 'lavadora', 'microondas', 'licuadora', 'estufa nueva', 'freidora de aire', 'aspiradora']],
  ['housing', 'house_moving', ['mudanza', 'flete', 'camioneta de mudanza', 'cajas para la mudanza']],
  ['housing', 'house_security', ['alarma', 'cámaras de seguridad', 'caseta de vigilancia', 'cerradura nueva', 'monitoreo de alarma']],
  ['housing', 'house_laundry_service', ['lavandería', 'tintorería', 'lavado de ropa', 'planchado', 'lavar las cobijas en la lavandería']],

  // ---------- Comida y bebidas ----------
  ['food', 'food_supermarket', ['el súper', 'walmart', 'soriana', 'despensa', 'mandado', 'costco', 'chedraui', 'leche y huevo', 'verduras y fruta', 'carne para la semana', 'tortillas', 'jitomate', 'aguacate', 'arroz y frijol', 'papel de baño', 'detergente']],
  ['food', 'food_restaurant', ['comida en restaurante', 'vips', 'toks', 'sanborns', 'cena en restaurante', 'desayuno en el restaurante', 'comida corrida', 'comida en la fonda']],
  ['food', 'food_coffee', ['café', 'starbucks', 'un latte', 'capuchino', 'café de grano', 'nescafé', 'un americano', 'chai latte', 'un frappé']],
  ['food', 'food_alcohol', ['cerveza', 'unas chelas', 'copas', 'vino tinto', 'tequila', 'whisky', 'six de cervezas', 'mezcal', 'caguama', 'botella de ron']],
  ['food', 'food_fastfood', ['mcdonalds', 'burger king', 'tacos de pastor', 'tacos', 'una torta', 'hamburguesa', 'pizza', 'tamales', 'elotes', 'hot dogs', 'quesadillas', 'tacos de suadero', 'kfc']],
  ['food', 'food_snacks', ['botana', 'papitas', 'doritos', 'chicharrón', 'cacahuates', 'frituras', 'takis', 'cheetos']],
  ['food', 'food_sweets', ['dulces', 'chocolates', 'galletas', 'helado', 'paletas', 'un churro', 'nieve', 'gomitas']],
  ['food', 'food_delivery', ['uber eats', 'rappi', 'didi food', 'pedido a domicilio', 'comida a domicilio', 'delivery']],
  ['food', 'food_market', ['mercado', 'tianguis', 'mercado sobre ruedas', 'frutas en el mercado']],
  ['food', 'food_bakery', ['panadería', 'pan', 'pan dulce', 'bolillos', 'cuernitos']],
  ['food', 'food_organic', ['productos orgánicos', 'comida orgánica', 'proteína', 'dieta keto', 'tienda naturista']],
  ['food', 'food_juice_bar', ['jugo natural', 'licuado', 'smoothie', 'juguería', 'jugo de naranja']],
  ['food', 'food_catering', ['banquete', 'catering', 'buffet para el evento', 'mesa de dulces', 'taquiza para la fiesta']],
  ['food', 'food_water_delivery', ['garrafón', 'garrafón a domicilio', 'repartidor de agua', 'agua de garrafón']],

  // ---------- Entretenimiento ----------
  ['entertainment', 'ent_cinema', ['cine', 'cinépolis', 'cinemex', 'boletos de la película', 'palomitas del cine', 'película']],
  ['entertainment', 'ent_concerts', ['concierto', 'ticketmaster', 'festival', 'toquín', 'boletos del concierto', 'entradas al festival']],
  ['entertainment', 'ent_hobbies', ['mi hobby', 'pasatiempo', 'hobbies', 'cosas de mi pasatiempo']],
  ['entertainment', 'ent_videogames', ['videojuego', 'steam', 'playstation', 'xbox', 'nintendo', 'un juego de ps5', 'juego de switch']],
  ['entertainment', 'ent_sports', ['gimnasio', 'gym', 'smart fit', 'cancha de fútbol', 'renta de cancha', 'clase de box', 'clase de crossfit', 'mensualidad del gym']],
  ['entertainment', 'ent_bowling', ['boliche', 'pista de boliche', 'una partida de boliche', 'boliche con amigos']],
  ['entertainment', 'ent_clubs', ['antro', 'discoteca', 'cover', 'bar', 'cantina', 'botanero', 'el antro con amigos']],
  ['entertainment', 'ent_streaming', ['netflix', 'disney+', 'hbo max', 'spotify', 'youtube premium', 'prime video', 'apple tv', 'streaming', 'crunchyroll']],
  ['entertainment', 'ent_subscriptions', ['suscripción', 'membresía', 'suscripción mensual']],
  ['entertainment', 'ent_events', ['evento', 'teatro', 'museo', 'partido de fútbol', 'estadio', 'boletos del partido', 'obra de teatro', 'exposición']],
  ['entertainment', 'ent_karaoke', ['karaoke', 'noche de karaoke', 'karaoke con amigos']],
  ['entertainment', 'ent_amusement', ['parque de diversiones', 'feria', 'six flags', 'entradas a la feria', 'parque acuático']],
  ['entertainment', 'ent_escape_room', ['cuarto de escape', 'escape room', 'escape room con amigos']],
  ['entertainment', 'ent_arcade', ['arcada', 'maquinitas', 'fichas de arcada', 'vr arena']],
  ['entertainment', 'ent_billiards', ['billar', 'pool', 'dominó', 'mesa de billar']],
  ['entertainment', 'ent_photography', ['fotógrafo', 'cabina de fotos', 'recuerditos', 'photobooth', 'sesión de fotos']],

  // ---------- Estilo de vida ----------
  ['lifestyle', 'life_gifts', ['regalo', 'regalo de cumpleaños', 'intercambio navideño', 'un regalo para mi novia']],
  ['lifestyle', 'life_pets', ['croquetas', 'veterinario', 'comida del perro', 'arena para el gato', 'mi mascota', 'vacunas del perro', 'peluquería canina', 'juguete para el perro']],
  ['lifestyle', 'life_donations', ['donación', 'donativo', 'colecta', 'donación a la cruz roja']],
  ['lifestyle', 'life_travel', ['hotel', 'airbnb', 'reservación de hotel', 'hostal', 'hospedaje en la playa']],
  ['lifestyle', 'life_experiences', ['tour', 'escapada de fin de semana', 'paseo en globo', 'tour gastronómico']],
  ['lifestyle', 'life_family_support', ['le di a mi mamá', 'le di a mi papá', 'apoyo familiar', 'ayuda para mi familia', 'le mandé dinero a mi mamá']],
  ['lifestyle', 'life_community', ['voluntariado', 'causa comunitaria', 'cooperación para la limpieza de la colonia', 'faena vecinal']],
  ['lifestyle', 'life_celebration', ['posada', 'celebración', 'cumpleaños familiar', 'cena de navidad', 'comida del día de las madres']],
  ['lifestyle', 'life_self_improvement', ['coaching', 'desarrollo personal', 'retiro espiritual', 'taller de meditación']],
  ['lifestyle', 'life_social_clubs', ['club social', 'membresía del club', 'country club', 'cuota del club', 'cuota del club de golf']],
  ['lifestyle', 'life_wedding', ['boda', 'despedida de soltero', 'despedida de soltera', 'xv años', 'baby shower', 'regalo de boda', 'vestido de novia']],

  // ---------- Salud ----------
  ['health', 'health_doctor', ['doctor', 'consulta médica', 'análisis', 'pediatra', 'consulta con el médico general', 'urgencias']],
  ['health', 'health_pharmacy', ['farmacia', 'medicina', 'farmacia del ahorro', 'pastillas', 'medicinas', 'jarabe', 'paracetamol', 'similares', 'antibiótico']],
  ['health', 'health_dentist', ['dentista', 'ortodoncista', 'limpieza dental', 'caries', 'endodoncia', 'brackets', 'consulta con el dentista']],
  ['health', 'health_mental', ['psicólogo', 'terapia', 'psiquiatra', 'terapeuta', 'sesión con la psicóloga', 'terapia de pareja']],
  ['health', 'health_hygiene', ['toallas femeninas', 'tampones', 'copa menstrual', 'condones', 'preservativos']],
  ['health', 'health_insurance', ['seguro médico', 'seguro de gastos médicos', 'sgmm', 'póliza de salud']],
  ['health', 'health_vision', ['óptica', 'lentes', 'anteojos', 'armazones', 'lentes de contacto', 'graduación de lentes', 'lentes nuevos']],
  ['health', 'health_supplements', ['vitaminas', 'suplementos', 'omega 3', 'magnesio', 'colágeno', 'vitamina d', 'multivitamínico']],
  ['health', 'health_specialists', ['podólogo', 'oftalmólogo', 'dermatólogo', 'nutriólogo', 'fisioterapeuta', 'optometrista', 'cardiólogo', 'ginecólogo', 'traumatólogo']],
  ['health', 'health_labs', ['estudios clínicos', 'análisis de sangre', 'rayos x', 'ultrasonido', 'resonancia', 'tomografía', 'examen de sangre', 'electrocardiograma']],

  // ---------- Transporte ----------
  ['transport', 'trans_uber', ['uber', 'un uber', 'uber al trabajo', 'uber a casa']],
  ['transport', 'trans_didi', ['didi', 'un didi', 'didi a la oficina']],
  ['transport', 'trans_taxi', ['taxi', 'indriver', 'cabify', 'taxi al aeropuerto', 'un taxi']],
  ['transport', 'trans_public', ['metro', 'camión', 'metrobús', 'transporte público', 'tarjeta del metro', 'pasaje', 'cablebús', 'tren ligero', 'trolebús']],
  ['transport', 'trans_gas', ['gasolina', 'gasolinera', 'magna', 'premium', 'diesel', 'tanque lleno', 'carga de gasolina', 'litros de gasolina']],
  ['transport', 'trans_flights', ['vuelo', 'avión', 'aeroméxico', 'volaris', 'vivaaerobus', 'boletos de avión', 'vuelo a monterrey']],
  ['transport', 'trans_carrental', ['renta de coche', 'renta de auto', 'hertz', 'renta de camioneta']],
  ['transport', 'trans_parking', ['estacionamiento', 'pensión', 'parquímetro', 'viene viene', 'franelero', 'valet parking']],
  ['transport', 'trans_tolls', ['peaje', 'caseta', 'tag', 'iave', 'casetas a cuernavaca', 'caseta de cobro']],
  ['transport', 'trans_maintenance', ['taller', 'mantenimiento del coche', 'mecánico', 'refacción', 'llanta nueva', 'talacha', 'cambio de aceite', 'afinación', 'frenos']],
  ['transport', 'trans_school', ['transporte escolar', 'camión escolar', 'la ruta de la escuela']],
  ['transport', 'trans_microbus', ['micro', 'microbús', 'pesero', 'pecera', 'colectivo']],
  ['transport', 'trans_combi', ['combi', 'la combi', 'combi a la escuela']],
  ['transport', 'trans_bikeshare', ['ecobici', 'scooter', 'bici pública', 'renta de scooter']],
  ['transport', 'trans_mototaxi', ['mototaxi', 'moto taxi', 'motorratón', 'un mototaxi']],
  ['transport', 'trans_ferry', ['ferry', 'lancha', 'transbordador', 'panga', 'boleto del ferry']],
  ['transport', 'trans_car_insurance', ['seguro de auto', 'seguro del carro', 'póliza de auto', 'gnp auto', 'qualitas', 'seguro del coche']],
  ['transport', 'trans_bike', ['bicicleta', 'refacciones de bici', 'candado de bici', 'casco de bici', 'luces para la bici']],

  // ---------- Deudas ----------
  ['debt', 'debt_creditcard', ['tarjeta de crédito', 'pago de la tarjeta', 'pago mínimo', 'abono a la tarjeta de crédito', 'pago para no generar intereses']],
  ['debt', 'debt_student', ['préstamo estudiantil', 'crédito educativo', 'crédito estudiantil']],
  ['debt', 'debt_personal', ['préstamo personal', 'prestamista', 'tanda', 'pago de mi tanda', 'abono del préstamo']],
  ['debt', 'debt_car_loan', ['crédito auto', 'crédito automotriz', 'mensualidad del carro', 'pago del crédito del coche', 'abono del auto']],
  ['debt', 'debt_appliance', ['crédito de muebles', 'a meses sin intereses', 'coppel', 'elektra', 'pago de coppel', 'abono a elektra']],
  ['debt', 'debt_payday_loan', ['empeño', 'monte de piedad', 'préstamo de nómina', 'crédito rápido', 'prestaentresemana']],
  ['debt', 'debt_medical', ['deuda médica', 'plan de pagos del hospital', 'financiamiento médico', 'pago de la cuenta del hospital']],

  // ---------- Educación ----------
  ['education', 'edu_tuition', ['colegiatura', 'inscripción', 'la colegiatura de la universidad', 'inscripción de la prepa', 'cuota de la facultad', 'reinscripción']],
  ['education', 'edu_supplies', ['copias', 'impresiones', 'engargolado', 'papelería', 'libros', 'plumones', 'útiles escolares', 'cuadernos', 'mochila para la escuela']],
  ['education', 'edu_courses', ['curso', 'diplomado', 'examen de certificación', 'platzi', 'udemy', 'curso de inglés', 'coursera', 'certificación de excel']],
  ['education', 'edu_tutoring', ['clases particulares', 'regularización', 'tutor', 'asesoría escolar']],
];
